### ISSUE TITLE
Where is code?

### ISSUE THREAD

**Issue by wbsdty331** [holalula/HaiBinQiangJia#1]
This repo just have some screenshots?

**Comment by holalula** [comment]
soon

**Comment by wbsdty331** [comment]
Another question:
your tool based on `bdth` but bdth's license is mit

**Comment by holalula** [comment]
i dont know about `bdth`, what's the full name

**Comment by DieMoe233** [comment]
> i dont know about `bdth`, what's the full name

LeonBlade/BurningDownTheHouse
