### ISSUE TITLE
源文件不完整，没法民间开源接力

### ISSUE THREAD

**Issue by DaPaoStudio** [holalula/HaiBinQiangJia#14]
作者大大你好，我是某不知名技校SE大四学生，下载了源码本想试试能不能改动以适配新版本并提交pull request，发现与QT的UI有关的头文件有大量缺失，若作者方便希望能联系Q353276133进行些许交流

**Comment by HEVAM** [comment]
UI文件不完整没啥吧，可以自己搞一下UI嘛，反正他那个UI也等于没搞
